inherits = 'rasmus'

"ui.background" = {}
"ui.cursor" = { fg = 'gray01',  bg = 'yellow' }
"attribute" = {fg = 'cherry'}
"constructor" = {fg = 'bright_cyan', modifiers = ['italic']}
"tag" = {fg = 'blue'}
"keyword" = {fg = 'red'}
function = {fg = 'yellow', modifiers = ['bold']}

[palette]
bg = "#1a1a19"
fg = "#d1d1d1"
black = "#333332"
red = "#ff968c"
green = "#61957f"
yellow = "#ffc591"
blue = "#8db4d4"
magenta = "#de9bc8"
cyan = "#7bb099"
white = "#d1d1d1"
bright_black = "#4c4c4b"
bright_red = "#ffafa5"
bright_green = "#7aae98"
bright_yellow = "#ffdeaa"
bright_blue = "#a6cded"
bright_magenta = "#f7b4e1"
bright_cyan = "#94c9b2"
bright_white = "#eaeaea"
gray01 = "#222221"
gray02 = "#2a2a29"
gray03 = "#323231"
gray04 = "#3a3a39"
gray05 = "#6a6a69"
gray06 = "#767675"
gray07 = "#b6b6b5"
